# Site settings
title: "Felipe Trevisan | Full Stack Developer"
description: "Felipe Trevisan, desenvolvedor Full Stack com mais de 9 anos de experiência em desenvolvimento de sistemas."
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: "Felipe Trevisan"
user_description: "Desenvolvedor Full Stack, autodidata. Atua há mais de 9 anos com desenvolvimento de sistemas na linguagem PHP. Agora trabalhando principalmente com tecnologias como: <u>AngularJS</u>, <u>NodeJS</u>, <u>React</u> e <u>React Native</u>. No seu tempo livre, assiste Netflix, joga videogames e fica com sua família e amigos, gosta de pesquisar sobre games, astronomia e principalmente tecnologias."
user_title: "Full Stack Developer"
email: "felipejs@gmail.com"
facebook_username: "felipecolucci"
linkedin_username: "felipeta"
github_username:  "felipetrevisan"

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
